[theme]
base="light"
primaryColor="#1f77b4"
backgroundColor="#ffffff"
secondaryBackgroundColor="#1f77b4"
textColor="#000000"

[server]
maxUploadSize = 12072

export STREAMLIT_SERVER_MAX_UPLOAD_SIZE=12072
